import type { Course } from "./types";

// 假資料：Supabase 的 courses 資料表還沒合進 main 前先用這份。
// 換真資料時不用改這個檔，改 lib/courses/getCourses.ts 即可。
// 教練的頭像、認證、Tag、評價也是假資料；頭像先全部留空，卡片會顯示姓名首字。
export const MOCK_COURSES: Course[] = [
  {
    id: "c1",
    title: "羽球基礎步法與發球",
    sport: "羽球",
    city: "台北市",
    district: "大安區",
    venue: "大安運動中心",
    startsAt: "2026-10-10T19:00:00+08:00",
    level: "beginner",
    coachId: "coach-lin",
    coachName: "林教練",
    coachPhotoUrl: null,
    coachVerified: true,
    coachTags: ["新手友善", "重視基礎"],
    coachRating: 4.9,
    coachReviewCount: 84,
    price: 450,
    enrolled: 6,
    minToOpen: 4,
    capacity: 8,
  },
  {
    id: "c2",
    title: "晨間流動瑜珈",
    sport: "瑜珈",
    city: "台北市",
    district: "松山區",
    venue: "松山文創園區",
    startsAt: "2026-10-11T08:00:00+08:00",
    level: "beginner",
    coachId: "coach-chen",
    coachName: "陳老師",
    coachPhotoUrl: null,
    coachVerified: true,
    coachTags: ["女性友善", "舒壓放鬆", "氣氛輕鬆"],
    coachRating: 5.0,
    coachReviewCount: 112,
    price: 380,
    enrolled: 2,
    minToOpen: 5,
    capacity: 10,
  },
  {
    id: "c3",
    title: "抱石入門：手點與腳法",
    sport: "抱石",
    city: "新北市",
    district: "板橋區",
    venue: "板橋岩館",
    startsAt: "2026-10-12T14:00:00+08:00",
    level: "beginner",
    coachId: "coach-wang",
    coachName: "王教練",
    coachPhotoUrl: null,
    coachVerified: true,
    coachTags: ["動作矯正", "專項訓練"],
    coachRating: 4.8,
    coachReviewCount: 45,
    price: 600,
    enrolled: 4,
    minToOpen: 4,
    capacity: 6,
  },
  {
    id: "c4",
    title: "重訓徒手核心強化",
    sport: "重訓",
    city: "台中市",
    district: "西屯區",
    venue: "西屯健身中心",
    startsAt: "2026-10-13T19:30:00+08:00",
    level: "intermediate",
    coachId: "coach-zhang",
    coachName: "張教練",
    coachPhotoUrl: null,
    coachVerified: false,
    coachTags: ["增肌", "肌力提升", "嚴格扎實", "提供器材"],
    coachRating: 4.6,
    coachReviewCount: 12,
    price: 500,
    enrolled: 8,
    minToOpen: 6,
    capacity: 8,
  },
  {
    id: "c5",
    title: "匹克球發球與落點進階",
    sport: "匹克球",
    city: "台北市",
    district: "內湖區",
    venue: "內湖匹克球場",
    startsAt: "2026-10-17T15:00:00+08:00",
    level: "advanced",
    coachId: "coach-li",
    coachName: "李教練",
    coachPhotoUrl: null,
    coachVerified: true,
    coachTags: ["上班族", "氣氛輕鬆"],
    coachRating: 4.7,
    coachReviewCount: 28,
    price: 800,
    enrolled: 1,
    minToOpen: 3,
    capacity: 4,
  },
  {
    id: "c6",
    title: "衝浪陸上訓練與入門",
    sport: "衝浪",
    city: "新北市",
    district: "貢寮區",
    venue: "福隆海水浴場",
    startsAt: "2026-10-18T09:00:00+08:00",
    level: "beginner",
    coachId: "coach-huang",
    coachName: "黃教練",
    coachPhotoUrl: null,
    coachVerified: true,
    coachTags: ["新手友善", "中英雙語", "提供器材"],
    coachRating: 4.9,
    coachReviewCount: 63,
    price: 1200,
    enrolled: 5,
    minToOpen: 5,
    capacity: 8,
  },
  {
    id: "c7",
    title: "排球接發球與傳球基礎",
    sport: "排球",
    city: "高雄市",
    district: "左營區",
    venue: "巨蛋體育館",
    startsAt: "2026-10-20T20:00:00+08:00",
    level: "intermediate",
    coachId: "coach-wu",
    coachName: "吳教練",
    coachPhotoUrl: null,
    coachVerified: false,
    coachTags: ["重視基礎", "台語也會通"],
    coachRating: null,
    coachReviewCount: 0,
    price: 350,
    enrolled: 10,
    minToOpen: 6,
    capacity: 10,
  },
  {
    id: "c8",
    title: "瑜珈核心與伸展",
    sport: "瑜珈",
    city: "台中市",
    district: "西區",
    venue: "勤美綠園道教室",
    startsAt: "2026-10-21T10:00:00+08:00",
    level: "intermediate",
    coachId: "coach-zhou",
    coachName: "周老師",
    coachPhotoUrl: null,
    coachVerified: true,
    coachTags: ["產後恢復", "耐心細心", "舒壓放鬆"],
    coachRating: 4.9,
    coachReviewCount: 71,
    price: 420,
    enrolled: 3,
    minToOpen: 4,
    capacity: 8,
  },
  {
    id: "c9",
    title: "跑酷基礎：翻越與落地",
    sport: "跑酷",
    city: "高雄市",
    district: "鼓山區",
    venue: "鼓山運動公園",
    startsAt: "2026-10-24T15:00:00+08:00",
    level: "beginner",
    coachId: "coach-zheng",
    coachName: "鄭教練",
    coachPhotoUrl: null,
    coachVerified: false,
    coachTags: ["專項訓練", "運動傷害預防"],
    coachRating: 4.5,
    coachReviewCount: 9,
    price: 700,
    enrolled: 2,
    minToOpen: 3,
    capacity: 6,
  },
  // 以下兩門課的程度是「不限」，用來確認程度篩選選「不限」時只會篩出它們
  {
    id: "c10",
    title: "排球臨打大亂鬥",
    sport: "排球",
    city: "台北市",
    district: "信義區",
    venue: "信義國小體育館",
    startsAt: "2026-10-18T19:00:00+08:00",
    level: "unlimited",
    coachId: "coach-lin",
    coachName: "林教練",
    coachPhotoUrl: null,
    coachVerified: true,
    coachTags: ["新手友善", "重視基礎"],
    coachRating: 4.9,
    coachReviewCount: 84,
    price: 250,
    enrolled: 6,
    minToOpen: 6,
    capacity: 12,
  },
  {
    id: "c11",
    title: "羽球雙打自由配對",
    sport: "羽球",
    city: "新北市",
    district: "板橋區",
    venue: "板橋體育館",
    startsAt: "2026-10-23T19:30:00+08:00",
    level: "unlimited",
    coachId: "coach-xu",
    coachName: "許教練",
    coachPhotoUrl: null,
    coachVerified: false,
    coachTags: ["氣氛輕鬆", "上班族", "中英雙語", "提供器材"],
    coachRating: 4.6,
    coachReviewCount: 12,
    price: 300,
    enrolled: 2,
    minToOpen: 4,
    capacity: 10,
  },
];
