import type { Course } from "./types";

// 假資料：Supabase 的 courses 資料表還沒合進 main 前先用這份。
// 換真資料時不用改這個檔，改 lib/courses/getCourses.ts 即可。
export const MOCK_COURSES: Course[] = [
  {
    id: "c1",
    title: "羽球基礎步法與發球",
    sport: "羽毛球",
    city: "台北市",
    venue: "大安運動中心",
    startsAt: "2026-10-10T19:00:00+08:00",
    timeSlot: "evening",
    level: "beginner",
    coachName: "林教練",
    price: 450,
    enrolled: 6,
    minToOpen: 4,
    capacity: 8,
  },
  {
    id: "c2",
    title: "晨間流動瑜伽",
    sport: "瑜伽 / 普拉提",
    city: "台北市",
    venue: "松山文創園區",
    startsAt: "2026-10-11T08:00:00+08:00",
    timeSlot: "morning",
    level: "beginner",
    coachName: "陳老師",
    price: 380,
    enrolled: 2,
    minToOpen: 5,
    capacity: 10,
  },
  {
    id: "c3",
    title: "抱石入門：手點與腳法",
    sport: "抱石攀岩",
    city: "新北市",
    venue: "板橋岩館",
    startsAt: "2026-10-12T14:00:00+08:00",
    timeSlot: "afternoon",
    level: "beginner",
    coachName: "王教練",
    price: 600,
    enrolled: 4,
    minToOpen: 4,
    capacity: 6,
  },
  {
    id: "c4",
    title: "重訓徒手核心強化",
    sport: "重訓 fitness",
    city: "台中市",
    venue: "西屯健身中心",
    startsAt: "2026-10-13T19:30:00+08:00",
    timeSlot: "evening",
    level: "intermediate",
    coachName: "張教練",
    price: 500,
    enrolled: 8,
    minToOpen: 6,
    capacity: 8,
  },
  {
    id: "c5",
    title: "網球正手拍進階",
    sport: "網球",
    city: "台北市",
    venue: "內湖網球場",
    startsAt: "2026-10-17T15:00:00+08:00",
    timeSlot: "afternoon",
    level: "advanced",
    coachName: "李教練",
    price: 800,
    enrolled: 1,
    minToOpen: 3,
    capacity: 4,
  },
  {
    id: "c6",
    title: "衝浪陸上訓練與入門",
    sport: "衝浪水上",
    city: "新北市",
    venue: "福隆海水浴場",
    startsAt: "2026-10-18T09:00:00+08:00",
    timeSlot: "morning",
    level: "beginner",
    coachName: "黃教練",
    price: 1200,
    enrolled: 5,
    minToOpen: 5,
    capacity: 8,
  },
  {
    id: "c7",
    title: "籃球 3 對 3 戰術",
    sport: "籃球",
    city: "高雄市",
    venue: "巨蛋體育館",
    startsAt: "2026-10-20T20:00:00+08:00",
    timeSlot: "evening",
    level: "intermediate",
    coachName: "吳教練",
    price: 350,
    enrolled: 10,
    minToOpen: 6,
    capacity: 10,
  },
  {
    id: "c8",
    title: "普拉提墊上核心",
    sport: "瑜伽 / 普拉提",
    city: "台中市",
    venue: "勤美綠園道教室",
    startsAt: "2026-10-21T10:00:00+08:00",
    timeSlot: "morning",
    level: "intermediate",
    coachName: "周老師",
    price: 420,
    enrolled: 3,
    minToOpen: 4,
    capacity: 8,
  },
];
